export interface newUserType {
    fullName: string,
    dateOfBirth: Date | null,
    localGovt: string,
    stateOfOrigin: string,
    address: string,
    gender: string,
    phoneNumber: string,
    email: string,
    nationalIdentityNumber: string,
    employmentStatus: string,
    jobTitle: string,
    highestEducationLevel: string,
    password: string,
    terms?: true,
}